# Generated by Django 4.2.7 on 2023-11-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
